CREATE TABLE TBL_AUTHOR(
AUTHOR_ID INT PRIMARY KEY,
AUTHOR_NAME VARCHAR(30));
 
CREATE TABLE TBL_BOOK(
BOOK_ID INT PRIMARY KEY, 
BOOK_TITLE VARCHAR(30), 
AUTHOR_ID INT, 
FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_AUTHOR(AUTHOR_ID));

INSERT INTO TBL_AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES
(1, 'Likhil'),
(2, 'Abner'),
(3, 'Anurag');

INSERT INTO TBL_BOOK (BOOK_ID, BOOK_TITLE, AUTHOR_ID) VALUES
(101, 'Database', 1),
(102, 'OS', 2),
(103, 'CN', 3),
(104, 'ADBMS', 1),  
(105, 'ITPS', 2);

SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_AUTHOR;

SELECT B.BOOK_TITLE , A.AUTHOR_NAME
FROM TBL_BOOK AS B
INNER JOIN
TBL_AUTHOR AS A
ON 
B.AUTHOR_ID = A.AUTHOR_ID;